# Use root/example as user/password credentials
version: '3.1'

services:

  gin-members:
    container_name: gin-members
    restart: on-failure
    image: gin-members
    ports:
      - "8092:8080"
    environment:
      - MONGODB_HOST=mongodb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always